// src/dialogs/import-diagram-dialog/import-diagram-dialog.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { useDialog } from '@/hooks/use-dialog';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogInternalContent,
    DialogTitle,
} from '@/components/dialog/dialog';
import { Button } from '@/components/button/button';
import type { BaseDialogProps } from '../common/base-dialog-props';
import { useTranslation } from 'react-i18next';
import { FileUploader } from '@/components/file-uploader/file-uploader';
import { useStorage } from '@/hooks/use-storage';
import { useNavigate } from 'react-router-dom';
import { diagramFromJSONInput } from '@/lib/export-import-utils';
import { importCustomJson } from '@/lib/import-custom-json';
import { Alert, AlertDescription, AlertTitle } from '@/components/alert/alert';
import { AlertCircle } from 'lucide-react';

export interface ImportDiagramDialogProps extends BaseDialogProps {}

export const ImportDiagramDialog: React.FC<ImportDiagramDialogProps> = ({
    dialog,
}) => {
    const { t } = useTranslation();
    const [file, setFile] = useState<File | null>(null);
    const { addDiagram } = useStorage();
    const navigate = useNavigate();
    const [error, setError] = useState(false);

    const onFileChange = useCallback((files: File[]) => {
        if (files.length === 0) {
            setFile(null);
            return;
        }

        setFile(files[0]);
    }, []);

    useEffect(() => {
        if (!dialog.open) return;
        setError(false);
        setFile(null);
    }, [dialog.open]);
    const { closeImportDiagramDialog, closeCreateDiagramDialog } = useDialog();

    const handleImport = useCallback(() => {
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (e) => {
            const json = e.target?.result;
            if (typeof json !== 'string') return;

            try {
                // First try the standard ChartDB format
                let diagram;
                try {
                    diagram = diagramFromJSONInput(json);
                } catch {
                    // If that fails, try our custom format
                    try {
                        diagram = importCustomJson(json);
                    } catch {
                        // If both fail, show error
                        setError(true);
                        throw new Error('Invalid JSON format');
                    }
                }

                await addDiagram({ diagram });

                closeImportDiagramDialog();
                closeCreateDiagramDialog();

                navigate(`/diagrams/${diagram.id}`);
            } catch (e) {
                setError(true);
                throw e;
            }
        };
        reader.readAsText(file);
    }, [
        file,
        addDiagram,
        navigate,
        closeImportDiagramDialog,
        closeCreateDiagramDialog,
    ]);

    return (
        <Dialog
            {...dialog}
            onOpenChange={(open) => {
                if (!open) {
                    closeImportDiagramDialog();
                }
            }}
        >
            <DialogContent className="flex max-h-screen flex-col" showClose>
                <DialogHeader>
                    <DialogTitle>
                        {t('import_diagram_dialog.title')}
                    </DialogTitle>
                    <DialogDescription>
                        {t('import_diagram_dialog.description')}
                    </DialogDescription>
                </DialogHeader>
                <DialogInternalContent>
                    <div className="flex flex-col p-1">
                        <FileUploader
                            supportedExtensions={['.json']}
                            onFilesChange={onFileChange}
                        />
                        {error ? (
                            <Alert variant="destructive" className="mt-2">
                                <AlertCircle className="size-4" />
                                <AlertTitle>
                                    {t('import_diagram_dialog.error.title')}
                                </AlertTitle>
                                <AlertDescription>
                                    {t(
                                        'import_diagram_dialog.error.description'
                                    )}
                                </AlertDescription>
                            </Alert>
                        ) : null}
                    </div>
                </DialogInternalContent>
                <DialogFooter className="flex gap-1 md:justify-between">
                    <DialogClose asChild>
                        <Button variant="secondary">
                            {t('import_diagram_dialog.cancel')}
                        </Button>
                    </DialogClose>
                    <Button onClick={handleImport} disabled={file === null}>
                        {t('import_diagram_dialog.import')}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

// src/dialogs/import-diagram-dialog/ImportDiagramDialog.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
  DialogFooter,
  DialogInternalContent,
  DialogClose
} from '@/components/dialog'
import { Button } from '@/components/button'
import type { BaseDialogProps } from '../common/BaseDialogProps'
import { useTranslation } from 'vue-i18n'
import { FileUploader } from '@/components/file-uploader/FileUploader.vue'
import { useStorage } from '@/composables/useStorage'
import { useRouter } from 'vue-router'
import { diagramFromJSONInput } from '@/lib/export-import-utils'
import { importCustomJson } from '@/lib/import-custom-json'
import { Alert, AlertDescription, AlertTitle } from '@/components/alert'
import { AlertCircle } from 'lucide-vue-next'
import { useDialog } from '@/composables/useDialog'

interface ImportDiagramDialogProps extends BaseDialogProps {}

const props = defineProps<ImportDiagramDialogProps>()

const { t } = useTranslation()
const file = ref<File | null>(null)
const { addDiagram } = useStorage()
const router = useRouter()
const error = ref(false)

const { closeImportDiagramDialog, closeCreateDiagramDialog } = useDialog()

// 处理文件变化
const onFileChange = (files: File[]) => {
  if (files.length === 0) {
    file.value = null
    return
  }
  
  file.value = files[0]
}

// 监听对话框打开状态
watch(() => props.dialog?.open, (isOpen) => {
  if (isOpen) {
    error.value = false
    file.value = null
  }
}, { immediate: true })

// 处理导入
const handleImport = async () => {
  if (!file.value) return
  
  try {
    error.value = false
    
    const fileContent = await file.value.text()
    const diagram = diagramFromJSONInput(fileContent)
    
    if (!diagram) {
      error.value = true
      return
    }
    
    // 导入自定义JSON
    const importedDiagram = await importCustomJson(diagram)
    
    // 添加图表
    await addDiagram({ diagram: importedDiagram })
    
    // 关闭对话框
    closeImportDiagramDialog()
    closeCreateDiagramDialog()
    
    // 导航到新图表
    router.push(`/diagrams/${importedDiagram.id}`)
  } catch (e) {
    console.error('Error importing diagram:', e)
    error.value = true
  }
}

// 处理对话框打开状态变化
const handleOpenChange = (open: boolean) => {
  if (!open) {
    closeImportDiagramDialog()
  }
}
</script>

<template>
  <Dialog
    v-bind="props.dialog"
    @update:open="handleOpenChange"
  >
    <DialogContent class="flex max-h-screen flex-col" show-close>
      <DialogHeader>
        <DialogTitle>
          {{ t('import_diagram_dialog.title') }}
        </DialogTitle>
        <DialogDescription>
          {{ t('import_diagram_dialog.description') }}
        </DialogDescription>
      </DialogHeader>
      
      <DialogInternalContent>
        <div class="flex flex-col p-1">
          <FileUploader
            :supported-extensions="['.json']"
            @files-change="onFileChange"
          />
          
          <Alert v-if="error" variant="destructive" class="mt-2">
            <AlertCircle class="size-4" />
            <AlertTitle>
              {{ t('import_diagram_dialog.error.title') }}
            </AlertTitle>
            <AlertDescription>
              {{ t('import_diagram_dialog.error.description') }}
            </AlertDescription>
          </Alert>
        </div>
      </DialogInternalContent>
      
      <DialogFooter class="flex gap-1 md:justify-between">
        <DialogClose as-child>
          <Button variant="secondary">
            {{ t('import_diagram_dialog.cancel') }}
          </Button>
        </DialogClose>
        <Button @click="handleImport" :disabled="file === null">
          {{ t('import_diagram_dialog.import') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
